export default [
	'npm install',
	'npm update',
	'npm run compile',
	'npm run dev',
	'npm run serve',
	'npm run build',
	'npm run deploy',
	'npm run watch',
	'pm2 start all',
	'pm2 stop all',
	'pm2 list',
	'pm2 logs',
	'pm2 status',
	'vsce package',
];
