export default [
	'echo "321=welcome" | sudo -S service mongod start && pm2 start all',
	'npm run deploy:dev',
	'npm run deploy:doc',
	// high command lines
	'npm install',
	'npm run dev',
	'npm run serve',
	'npm run build',
	'npm run deploy',
	'npm run deploy:sl',
	'npm run sync',
	'npm install',
	'service mongod start',
	'pm2 start all',
	// devDependencies
	'-D eslint-config-teslint@latest',
	'-D @types/node',
	'-D gulp@^4.0.0 ',
	'-D gulp-autoprefixer',
	'-D gulp-babel',
	'-D gulp-clean-css',
	'-D gulp-htmlmin',
	'-D gulp-rename',
	'-D gulp-replace',
	'-D gulp-ssh',
	'-D gulp-strip-css-comments',
	'-D gulp-uglify',
	// dependencies
	'cheerio@^1.0.0-rc.2',
	'joi',
	'lodash',
	'md5',
	'moment',
	'nconf',
	'normalize.css',
	'request',
	'request-promise',
	'require-dir',
	'superagent',
	'superagent-charset',
	'-g gulp@^4.0.0',
	'-g lglong519/generator',
	'-g nodemon',
	'-g supervisor',
	'-g ts-node',
	'-g typings',
	'-g @vue/cli',
	'-g yo generator-code',
	// command lines
	'generator w i to o',
	'generator w o in i',
	'ssh ubuntu@devapi.edu.ink',
	'ssh root@mofunc.com',
	'vsce package'
];
